run:
  deadline: 30m
  tests: true

linters-settings:
  govet:
    check-shadowing: true
    fieldalignment: true
  gofmt:
    simplify: true
  maligned:
    suggest-new: true

linters:
  enable:
    - deadcode
    - dupl
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - prealloc
    - unconvert
  disable:
    - errcheck
