language: go

go:
- 1.15.x

install:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.38.0

script: make lint && make codecov && go build

after_success:
  - bash <(curl -s https://codecov.io/bash)
